excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://GustavoEmmel.github.io
title: Desenvolvimento Ágil
email: gremmel@gmail.com
author: Gustavo Reichelt Emmel
description: Aluno da Pos-Graduação UniRitter em Tecnologias Aplicadas a Sistema de Informação com Metodos Ageis.<br /><br />DESENVOLVEDOR PHP NA TECBIZ - TECNOLOGIA E NEGÓCIOS.
paginate: 5
google_analytics: 
